name: mobile_pointsale
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  dio: ^5.8.0+1
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.2.0
  path_provider: ^2.1.5
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: Saira
      fonts:
        - asset: assets/fonts/saira.ttf
          weight: 400
        - asset: assets/fonts/saira_bold.ttf
          weight: 700